# Generated by Django 6.0.4 on 2026-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Feriado')),
                ('dia', models.DateField(verbose_name='Data')),
                ('mes', models.DateField(verbose_name='Mês')),
            ],
        ),
    ]
