# Generated by Django 6.0.4 on 2026-04-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriadosmodel',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='modificado_em'),
        ),
    ]
