# Generated by Django 6.0.4 on 2026-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feriadosmodel_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadosmodel',
            name='dia',
            field=models.IntegerField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='feriadosmodel',
            name='mes',
            field=models.IntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='feriadosmodel',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado_em'),
        ),
    ]
