# Generated by Django 6.0.4 on 2026-04-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_feriadosmodel_dia_alter_feriadosmodel_mes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feriadosmodel',
            old_name='name',
            new_name='nome',
        ),
    ]
